#pragma once

#include "../tour/TourName.hpp"

class BsTelop
{
public:

	enum TelopName : u8
	{
		FRIEND_MATCH_ENTRY=0,
		FRIEND_MATCH_LEAVE=1,
		SAVE_CONTINUE=2,
		SAVE_INTERRUPT=3,
		RANDOM_MATCH_ENTRY=4,
		RANDOM_MATCH_SEE_OFF=5,
		PLEASE_END_CONVERSATION=6,
		PLEASE_CLOSE_WINDOW=7,
		SELECTION_CANCELED=8,
		BOAT_TRIP_NOTIFY=9,
		BOAT_TRIP_CANCELED=10,
		BOAT_TRIP_CANCELED_2=11,
		NAME_HAS_ARRIVED=12,
		WAITING_FOR_FRIENDS=13,
		FRIEND_MATCH_ENTRY_WHEN_ON_BOAT=14,
		NO_SD_CARD=15,
		SD_CARD_WRITE_PROTECTED=16,
		NO_SPACE_ON_SD_CARD=17,
		PHOTO_LIMIT=18,
		CANNOT_RECOGNIZE_SD=19,
		SD_CARD_ERROR=20,
		TOUR_DEPART_PARTICIPATING=21,
		TOUR_DEPARTING_SOON=22,
		TOUR_DEPART_NON_PARTICIPATING=23,
		TOUR_CANCEL=24,
		RETURN_TO_TOWN_REQUEST=25,
		RETURN_TO_TOWN_CANCELED=26,
		FRIEND_REGISTERED=27,
		ALMOST_OUT_OF_TIME=28,
		TOUR_TIME_UP=29,
		GAME_OVER=30,
		HIDE_AND_SEEK_START=31,
		HIDE_AND_SEEK_TIME_UP=32,
		WEEDING_START=33,
		WEEDING_STOP=34,
		WEEDING_STOP_2=35,
		TIMER_START=36,
		TIMER_STOP=37,
		TIMER_TIME_UP=38,
		STORE_NOT_STAFFED=39,
		NONE=40
	};

	static void ShowTelop(TelopName telop);
	static void ShowTourTelop(TelopName telop, TourName tour);

private:
};
